logging:
  level:
    org.springframework.web: ERROR
    com.mera: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d %-5level %logger : %msg%n"
  file:
    name: C:/NumberProject/logs